 version: "3"

 services:

    php:
        volumes:
            - "./php/:/var/www/html"
    db:
        ports:
            - "3306:3306"

    adminer:
        image: adminer
        container_name: esake_adminer
        ports:
        - "81:8080"