 version: "3"

 services:
    php:
        build: .
        container_name: esake_backend
        environment:
            - DB_HOST=db
            - DB_NAME=esakeDB
            - DB_USERNAME=root
            - DB_PASSWORD=changethispassword
        ports:
            - '80:80'
        depends_on:
            - db


    db:
        image: mariadb
        container_name: esake_db
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: 'changethispassword'

